# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-docstring-first

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

-   repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==23.1.0]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        types: [file, python]
        exclude: (.*/__init__.py|rlberry/check_packages.py)
        args: ['--select=F401,F405,D410,D411,D412']
- repo: local
  # We do not use pre-commit/mirrors-mypy, "./run-mypy"
  # as it comes with opinionated defaults
  # (like --ignore-missing-imports)
  # and is difficult to configure to run
  # with the dependencies correctly installed.
  hooks:
    - id: mypy
      name: mypy
      entry:  "./scripts/run_mypy.sh"
      language: python
      # use your preferred Python version
      language_version: python3.9
      additional_dependencies: ["mypy"]
      types: [python]
      # use require_serial so that script
      # is only called once per commit
      require_serial: true
      # Print the number of files as a sanity-check
      verbose: true
