trigger:
  paths:
    exclude:
    - rlberry/_version.py
    - docs

pr:
  paths:
    exclude:
    - rlberry/_version.py
    - docs

jobs:

- job: 'windows'
  dependsOn: checkPrLabel
  condition: or(in(variables['Build.SourceBranch'], 'refs/heads/main'), eq(dependencies.checkPrLabel.outputs['checkPrLabel.prHasCILabel'], true))
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      Python39:
        python.version: '3.9'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip wheel . -w dist\
      pip install --pre --no-index --find-links dist\ rlberry
    displayName: 'Install rlberry'

  - script: |
      pip install pytest==7.0.1 pytest-azurepipelines pytest-xvfb
      pytest -s --ignore=rlberry/network
    displayName: 'pytest'
