name: Version Control
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: actions/checkout@v2
        with:
          # This is necessary so that we have the tags.
          fetch-depth: 0
      - uses: mtkennerly/dunamai-action@v1
        with:
          env-var: MY_VERSION
      - run: echo $MY_VERSION

      - run: |
          echo "__version__ = \"$MY_VERSION \"" > rlberry/_version.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add rlberry/_version.py
          git commit -m "version"
          git push
