name: documentation_dev
on:
  pull_request_target:
    branches:
      - main
    types: [closed]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r main/docs/requirements.txt
          pip install -r main/requirements.txt
      - name: Sphinx build
        run: |
          sphinx-build main/docs _build
      - uses: actions/checkout@v4
        with:
          # This is necessary so that we have the tags.
          fetch-depth: 0
          ref: gh-pages
          path: gh_pages
      - name: Commit documentation changes
        run: |
          cd gh_pages 
          rm -r dev || echo "Ignoring exit status"
          mkdir dev
          cp -rv  ../_build/* dev
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Preview documentation"
          git push
