name: "preview"

on:
  workflow_run:
    workflows: ["ready_for_review"]
    types:
      - completed

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
          pip install -r requirements.txt
          sphinx-build docs _build

      - uses: actions/checkout@v3
        with:
          # This is necessary so that we have the tags.
          fetch-depth: 0
          ref: gh-pages
      - name: Commit documentation changes
        run: |
          rm -r preview_pr || echo "Ignoring exit status"
          mkdir preview_pr
          cp -r docs/_build/* preview_pr
      - uses: EndBug/add-and-commit@v8
        with:
          add: 'preview_pr'
          default_author: github_actor
          message: 'make preview of page'
