name: "preview"

on:
  workflow_run:
    workflows: ["ready_for_review"]
    types:
      - completed

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r main/docs/requirements.txt
          pip install -r main/requirements.txt
          sphinx-build main/docs _build

      - uses: actions/checkout@v4
        with:
          # This is necessary so that we have the tags.
          fetch-depth: 0
          ref: gh-pages
          path: gh_pages
      - name: Commit documentation changes
        run: |
          cd gh_pages 
          rm -r preview_pr || echo "Ignoring exit status"
          mkdir preview_pr
          cp -rv  ../_build/* preview_pr
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Preview documentation"
          git push
