name: ready_for_review

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]

jobs:
  build:
    if: contains( github.event.pull_request.labels.*.name, 'ready for review')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo ready for review!
