name: Trigger tests

on:
  pull_request:
    types:
      - labeled

permissions:
  pull-requests: write

jobs:
  add-comment:
    if: github.event.label.name == 'ready for review'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: EndBug/add-and-commit@v9
        with:
          commit: --allow-empty
          default_author: github_actor
          message: 'Trigger ci'
